- name: playbook
  hosts: webservers
  become: yes
  become_user: root
  gather_facts: no


  tasks:
        - name: install docker
          yum:
                  name: docker
                  state: present
        - name: start docker
          service:
                  name: docker
                  state: started
